runtime: nodejs8
beta_settings:
    cloud_sql_instances: mygameslist-217906:australia-southeast1:mygameslist
env_variables:
    PROJECT_NAME: mygameslist
    SQL_USER: root
    SQL_PASSWORD: 327
    SQL_DATABASE: mygameslist
    INSTANCE_CONNECTION_NAME: mygameslist-217906:australia-southeast1:mygameslist